Chat pagination
tomermoshe/Rocket.Chat.PWA pull request #15
Opened 2017-06-08 07:58 UTC by tomermoshe

2017-06-08 12:46 UTC, eitanfr commented on mock-server/index.ts
> +declare module 'graphql' {
add types.d.ts

2017-06-08 12:46 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.html
> +  <div class="loading-spinner">
check why it takes a few seconds to the spinner to appear.

2017-06-08 12:46 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
> +  public channel = { id: '1', name: '' };
why?

2017-06-08 13:35 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
> +        setTimeout(() => {
why setTimout 0?
and if must use it then use setImediate()

2017-06-08 13:35 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
> +      this.loading = loading;
remove loading

2017-06-08 13:35 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
>  export class ChatViewComponent implements OnInit, OnDestroy {
consider using ON_PUSH

2017-06-08 13:35 UTC, eitanfr commented on src/app/chat/main-page/main-page.component.ts
>    public channels = [
delete channels

2017-06-08 13:35 UTC, eitanfr commented on src/app/chat/main-page/main-page.component.ts
> +    if (window.outerWidth < 767) {
after you resize the menu btn doesn't work

2017-06-08 13:35 UTC, eitanfr commented on src/app/chat/services/chat/chat.service.ts
> +  private user = { name: undefined, avatar: undefined };
you can remove this initial user because you init the user in the constructor

2017-06-08 13:35 UTC, eitanfr commented on src/app/chat/services/chat/chat.service.ts
> +          this.noMoreToLoad = true;
maybe the scheme should contain `hasMore` filed, what do u think??

2017-06-08 13:35 UTC, eitanfr commented on src/app/graphql/client/apollo-client.ts
> +const networkInterface = createNetworkInterface({
what do think on changing the network interface to batching?

2017-06-08 13:44 UTC, tomermoshe commented on src/app/chat/chat-view/chat-view.component.ts
>  export class ChatViewComponent implements OnInit, OnDestroy {
done

2017-06-08 13:44 UTC, tomermoshe commented on src/app/chat/main-page/main-page.component.ts
>    public channels = [
done

2017-06-08 13:46 UTC, tomermoshe commented on src/app/chat/services/chat/chat.service.ts
> +          this.noMoreToLoad = true;
cursor is null when no more to load

2017-06-08 13:47 UTC, tomermoshe commented on src/app/chat/services/chat/chat.service.ts
> +  private user = { name: undefined, avatar: undefined };
it is init in subscribe - optimistic response can be used before subscribe is fired

2017-06-08 13:56 UTC, tomermoshe commented on src/app/graphql/client/apollo-client.ts
> +const networkInterface = createNetworkInterface({
another task

2017-06-08 14:07 UTC, tomermoshe commented on src/app/chat/chat-view/chat-view.component.ts
> +  public channel = { id: '1', name: '' };
another task

2017-06-09 14:43 UTC, tomermoshe commented on src/app/chat/main-page/main-page.component.ts
> +    if (window.outerWidth < 767) {
done

2017-06-09 14:47 UTC, tomermoshe commented on src/app/chat/chat-view/chat-view.component.html
> +  <div class="loading-spinner">
could not reproduce in serve:dist

2017-06-11 08:07 UTC, eitanfr requested changes

2017-06-11 08:07 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.html
> +    <ion-title># {{channel?.name || null}}</ion-title>
why did u use `|| null`? isnt `?.` is enough?

2017-06-11 08:07 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
> +      this.chatService.getChannelByName(channelName, isDirect).subscribe((channelData) => {
we can change to `getMessages(byChannelName, isDirect)` query instead of 2 doing 2 queries(getting the channelInfo and then getting the messages)

2017-06-11 08:07 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
> +          return;
handle channel not found- if user enters an invalid URL with unknown channel name we should show an appropriate message

2017-06-11 08:07 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
> +        Observable.fromEvent(this.chatContent.nativeElement, 'scroll').subscribe(() => {
does it mean that we dont use ngx-infinate ? 
if so should remove all it refs

2017-06-11 08:07 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
> +        Observable.fromEvent(this.chatContent.nativeElement, 'scroll').subscribe(() => {
does we need to subscribe to `scroll` every time the user change url?
because if the user only change url the element doesnt rerenders

2017-06-11 08:07 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
> +            setTimeout(() => {
why setTimeout? arent a zone triggered from the message arrival?
and if so you can use setImmediate

2017-06-11 08:07 UTC, eitanfr commented on src/app/chat/main-page/main-page.component.ts
> +    Observable.fromEvent(window, 'resize').subscribe(() => this.modifySidenavToSize());
fuck ionic

2017-06-11 08:20 UTC, tomermoshe commented on src/app/chat/chat-view/chat-view.component.html
> +    <ion-title># {{channel?.name || null}}</ion-title>
done

2017-06-11 08:24 UTC, tomermoshe commented on src/app/chat/chat-view/chat-view.component.ts
> +        Observable.fromEvent(this.chatContent.nativeElement, 'scroll').subscribe(() => {
done

2017-06-11 08:51 UTC, tomermoshe commented on src/app/chat/main-page/main-page.component.ts
> +    Observable.fromEvent(window, 'resize').subscribe(() => this.modifySidenavToSize());
lol

2017-06-11 08:51 UTC, tomermoshe commented on src/app/chat/chat-view/chat-view.component.ts
> +            setTimeout(() => {
dont use setimmediate - use process.nextTick instead

2017-06-11 08:57 UTC, tomermoshe commented on src/app/chat/chat-view/chat-view.component.ts
> +        Observable.fromEvent(this.chatContent.nativeElement, 'scroll').subscribe(() => {
fuck ngx-infinite-cock - removed

2017-06-11 09:17 UTC, tomermoshe commented on src/app/chat/chat-view/chat-view.component.ts
> +          return;
done

2017-06-11 10:24 UTC, eitanfr commented on src/app/chat/chat-view/chat-view.component.ts
> +            setTimeout(() => {
i didnt get you
1. process.nextTick? isnt it node function?
2.why setTimeout? arent a zone triggered from the message arrival?

2017-06-11 13:45 UTC, tomermoshe commented on src/app/chat/chat-view/chat-view.component.ts
> +            setTimeout(() => {
1. no. setImmediate is very poorly supported - only in edge in internet explorer: https://developer.mozilla.org/en/docs/Web/API/Window/setImmediate.
just use setTimeout.
2. i need this code to run after the view was rendered with the new messages.

2017-06-12 07:17 UTC, merged